name: Check_2

on:
  workflow_run:
    workflows:
      - 'Check'
    types:
      - 'completed'

jobs:
  check_test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    
    permissions:
      id-token: write
      contents: read
      checks: write
      statuses: write

    steps:
      - run: exit 1

      - uses: hkusu/status-create-action@v1
        if: always()
        with:
          sha: ${{ github.sha }}
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
