name: Check

on:
  push:

jobs:
  check_test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write
      statuses: write

    steps:

    - uses: hkusu/status-create-action@v1
      with:
        sha: ${{ github.sha }}
        state: pending # specify 'error', 'failure', 'pending', or 'success'
        target-url: http://ci.example.com # default: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        description: Running.. # option
        context: My Workflow # default: '${{ github.workflow }}'